[package]
name = "dex-pair"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
dex-pair-io.workspace = true
dex-factory-io.workspace = true
gear-lib.workspace = true
ft-main-io.workspace = true
primitive-types.workspace = true

[dev-dependencies]
gtest.workspace = true
gclient.workspace = true
gstd = { workspace = true, features = ["debug"] }
gear-core = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
subxt = { version = "0.27", default-features = false }
pretty_assertions = "1"
dex-factory = { path = "../factory" }
dex-factory-state = { path = "../factory/state" }
dex-pair-state = { path = "state" }
sp-core-hashing = "6"
tokio = "1"

[build-dependencies]
gear-wasm-builder.workspace = true
dex-pair-io.workspace = true

[features]
binary-vendor = []
