[workspace]
resolver = "2"
members = [
    "factory",
    "factory/state",
    "pair",
    "pair/state",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[workspace.dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
gclient = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
gtest = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
gmeta = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
gstd = { git = "https://github.com/gear-tech/gear", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
ft-main-io = { git = "https://github.com/gear-dapps/sharded-fungible-token", tag = "2.1.1" }
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
dex-pair-io.path = "pair/io"
dex-factory-io.path = "factory/io"
hashbrown = "0.13"
primitive-types = { version = "0.12", default-features = false }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib", branch = "as-dev-dev" }
