[package]
name = "dex-factory"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
dex-factory-io.workspace = true
dex-pair-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
dex-factory-io.workspace = true
gmeta.workspace = true

[features]
binary-vendor = []
