[package]
name = "dex-factory"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git" }
dex-factory-io = { path = "../factory/io" }
dex-pair-io = { path = "../pair/io" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.0" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git"}

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }
